config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root to: 'stories#index'
    resources :stories, only: [:index, :show, :new, :create, :destroy]
    get '/users/:id/story_story', to: 'users#show_story', as: :show_story_user

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
    belongs_to :user
    has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!, only: [:home, :show, :index]


  def home
    @stories = Story.all
  end

  def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    @story.user = current_user
    if @story.save
      redirect_to story_path(@story)
    else
      render 'new'
    end
  end

  def destroy
    story = Story.find(params[:id])
    if current_user == story.user
      story.destroy
      redirect_to root_path
    else
      render(
        html: "<script>alert('You can't delete this motorcycle post because you are not the owner')</script>".html_safe,
        layout: 'application'
      )
    end
  end

  private


  def story_params
    params.require(:story).permit(:name, photos: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopifyImageRepository</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
        <%= render 'shared/navbar'%>
        <%= render 'shared/flashes'%>

    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://uploadpicture.gobbler.nl/wp-content/uploads/2018/09/upload_logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
        <a class="nav-link" href=""><%= link_to "Home", root_path %> </a>
        </li>
    
        <li class="nav-item dropdown">
          <%= image_tag "", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
           
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/stories/home.html.erb
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.pinimg.com/originals/2a/c4/77/2ac477bc2708882901461560be69b9ab.jpg);">

  <div class="container">
    <h1>Our stories</h1>
    <h3><%= link_to "Add a story", new_story_path, class: "btn btn-primary btn-lg" %></h3>
  </div>
</div>

app/views/stories/index.html.erb
  <h1>Image <span>Uploads</span></h1>

  <div class="container">

   <button type="button" class="btn btn-success"><%= link_to "Add a new picture", new_story_path %> </button>
<br>
<br>
    <div class="row">
      <% @stories.each do |story|%>
      <div class="col-12 col-md-6 col-lg-3">

      <div class="card-category"
      style="background-image: url('<%= cl_image_path story.photos[0].key, height: 200, width: 300, crop: :fill %>')">
      <%= link_to story.name.capitalize, story_path(story), class: "text-white text-decoration-none" %>
    </div>
    </div>

  <% end %>
  </div>

 <br>
</div>

app/views/stories/new.html.erb
<!-- app/views/restaurants/_form.html.erb -->
<div class="container">

<h1>My pictures </h1>
<h5>Add your travel pictures here</h5>
<%= simple_form_for(@story) do |f| %>
  <%= f.input :name %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>
</div>

app/views/stories/show.html.erb
<h1><%= @story.name %></h1>
<div class="container">

  <%= link_to "Back to all stories", stories_path %>
  <div class="row">
      <% if @story.photos.empty? %>
 <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path "https://res.cloudinary.com/dwxhfawho/image/upload/v1605666098/air-moto/2018_Aprilia_Shiver_900/2018_Aprilia_Shiver_900_1_aiz6s2.jpg", height: 300, width: 400, crop: :fill %>')">
    <% else %>
  <img class="d-block w-100"  src= "<%= cl_image_path @story.photos[0].key, crop: :fill %>", height: "300", width:"550">
  <br>
  <% end %>
<br>
<br>
   <%  if current_user == @story.user %>

   <%= link_to 'Delete this story', story_path(@story), method: :delete, :data => {:confirm => 'Are you sure? '}, class: "btn btn-success"%>
    <% end %>
</div>
</div>